### ISSUE TITLE
Error on Encountering New Frameboxes

### ISSUE THREAD

**Issue by Ruling-0** [GTNewHorizons/worldedit-gtnh#11]
With the work done in GTNH to move frameboxes to be dynamically TEs, the non-TE variant causes WE to error and cancel any operation upon encountering one in the scan. For example:

1. Use recent GTNH (this was Nightly 646)
2. Place some tungstensteel frame boxes
3. Place those boxes within a region (easiest is a line then pos1 a side pos2 the other)
4. //set 0
5. instant error and the frameboxes remain instead of becoming air

It gives an error "Can't have a block data value above 15 (316 given)", where 316 is tungensteel frame's metadata, but it works for other GT stuff which has much greater than 15 block data (such as basically any machine or pipe).

**Comment by Lyfts** [comment]
Fixed in https://github.com/GTNewHorizons/worldedit-gtnh/pull/9/files update to https://github.com/GTNewHorizons/worldedit-gtnh/releases/tag/v0.0.7
